# a git repo containing pre-commit plugins must contain a
# .pre-commit-hooks.yaml file that tells pre-commit which hooks are provided
# more details at https://pre-commit.com/#creating-new-hooks

- id: say-hello
  name: say hello
  description: a template to show how to implement a pre-commit hook
  language: python
  entry: say_hello.py
  require_serial: true
  pass_filenames: false
  args: ['OpenMMLab']

- id: check-readme
  name: check readme
  description: check whether the abstract and icon of algorithm is exist in readme
  language: python
  entry: check_readme.py
  require_serial: true
  pass_filenames: false
  args: ["--log-level", "INFO"]
